server:
  port: 8080
spring:
  sql:
    init:
      mode: never
  datasource:
    url: postgres://ilqcqvlwvygkal:5686e7ef58de2f027ab68aee76070dcf03b34cda2cf4ef779a8039f49e506756@ec2-52-210-97-223.eu-west-1.compute.amazonaws.com:5432/d7squkghvc36s4
    password: 5686e7ef58de2f027ab68aee76070dcf03b34cda2cf4ef779a8039f49e506756
    username: ilqcqvlwvygkal
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    properties:
#      mail:
#        smtp:
#          starttls:
#            required: true
#            enable: true
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#
#    username:
#    password:


#      shaxsiy variable lar
jwt:
  access:
    secret: buMeningParolim
  refresh:
    secret: buRefreshniParoli
twilio:
  accountSID: AC86501029b82f14ead7a91e2e3cd5669b
  authToken: b3e9d24140c99d8075807335ef74680a
  trialNumber: +17242046533