package pdp.com.appprojectexam.enums;

public enum PermissionEnum {

    VIEW_CATEGORY,
    ADD_CATEGORY,
    EDIT_CATEGORY,
    DELETE_CATEGORY,
    VIEW_PRODUCT,
    ADD_PRODUCT,
    EDIT_PRODUCT,
    DELETE_PRODUCT,

    VIEW_WAREHOUSE,
    ADD_WAREHOUSE,
    EDIT_WAREHOUSE,
    DELETE_WAREHOUSE,

    VIEW_CURRENCY,
    ADD_CURRENCY,
    EDIT_CURRENCY,
    DELETE_CURRENCY,

    VIEW_SUPPLIER,
    ADD_SUPPLIER,
    EDIT_SUPPLIER,
    DELETE_SUPPLIER,

    VIEW_MEASUREMENT,
    ADD_MEASUREMENT,
    EDIT_MEASUREMENT,
    DELETE_MEASUREMENT,

    VIEW_USER,
    EDIT_USER,
    DELETE_USER,
    MANAGE_ROLE_TO_USER,

    VIEW_ROLE,
    ADD_ROLE,
    EDIT_ROLE,
    DELETE_ROLE,
    ADD_PERMISSIONS_ROLE,
    DELETE_PERMISSIONS_ROLE,

    GET_ONE_INCOME_PRODUCT,
    ADD_INCOME_PRODUCT,
    EDIT_INCOME_PRODUCT,

    GET_ONE_OUTCOME_PRODUCT,
    ADD_OUTCOME_PRODUCT,
    EDIT_OUTCOME_PRODUCT,

    DOWNLOAD_ATTACHMENT,
    UPLOAD_ATTACHMENT,

    GET_ONE_INCOME_WAREHOUSE,
    ADD_INCOME_WAREHOUSE,

    GET_ONE_OUTCOME_WAREHOUSE,
    ADD_OUTCOME_WAREHOUSE

    ;

}
